line_length: 130

file_length:
  warning: 500
  error: 1200

disabled_rules:
  - identifier_name
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_first_last

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - ARCLTests
  - .build
